version: "3.9"

services:
  clonebot:
    image: ghcr.io/missemily2022/clonebot:new
    container_name: clonebot
    environment:
      - telegram_token=${BOT_TOKEN}
      - user_ids=${SUDO}
      - group_ids=${API_HASH}
      - PORT=${API_ID}
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
